### ISSUE TITLE
Error `Argument 1 passed to PHPHtmlParser\Dom::load() must be of the type string`

### ISSUE THREAD

**Issue by puleeno** [ramphor/rake-php#8]
# Logs:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPHtmlParser\Dom::load() must be of the type string, null given, called in /app-path/vendor/puleeno/rake-wordpress-adapter/src/ToothTrait.php on line 149 and defined in /app-path/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php:148
Stack trace:
#0 /app-path/vendor/puleeno/rake-wordpress-adapter/src/ToothTrait.php(149): PHPHtmlParser\Dom->load()
#1 [internal function]: Noithaticon_Spider_Tooth->updateContentImage()
#2 /app-path/vendor/puleeno/rake-wordpress-adapter/src/ToothTrait.php(137): call_user_func()
#3 /app-path/vendor/ramphor/rake/src/Resource.php(164): Noithaticon_Spider_Tooth->updateSystemResource()
#4 /app-path/vendor/ramphor/rake/src/Ab in /app-path/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php on line 148
```

**Comment by puleeno** [comment]
This error is not of Rake. It's an error of WordPress adapter. https://github.com/puleeno/rake-wordpress-adapter/issues/1
